title: Willyywt's blog # name of the site
author: Willy (Yang Wentao) # name of site's author
url: https://willyangywt.cc # root address of the site
description: > # description of the site (multiple lines allowed)
  Willyywt (aka yang wentao)'s personal blog.

favicon: "favicon.ico" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

permalink: /:year/:month/:day/:title:output_ext

show_excerpts: true
search_index: false

kramdown:
  # https://stackoverflow.com/a/25597026/17956106
  smart_quotes: ["apos", "apos", "quot", "quot"]

# Use rouge as syntax highlighter. (The original moving theme use https://highlightjs.org embeded in <head>)
# See rouge documentation: https://kramdown.gettalong.org/syntax_highlighter/rouge.html
# and jekyll documentation: https://jekyllrb.com/docs/liquid/tags/#code-snippet-highlighting
# The CSS stylesheet comes from https://github.com/jwarby/jekyll-pygments-themes; a preview is avaliable at https://spsarolkar.github.io/rouge-theme-preview/
syntax_highlighter: rouge

moving:
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
