title: Willyywt's blog # name of the site
author: Willy (Yang Wentao) # name of site's author
email: 22425315+willyywt@users.noreply.github.com # email of site's author
url: https://willyangywt.cc # root address of the site
description: > # description of the site (multiple lines allowed)
  Willyywt (aka yang wentao)'s personal blog.

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

show_excerpts: true

# if you want to publish to Github Pages, change "theme: moving" to "remote_theme: huangyz0918/moving"
remote_theme: huangyz0918/moving

moving:
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
