title: Willyywt's blog # name of the site
author: Willy (Yang Wentao) # name of site's author
url: https://willyangywt.cc # root address of the site
description: > # description of the site (multiple lines allowed)
  Willyywt (aka yang wentao)'s personal blog.

favicon: "favicon.ico" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

permalink: /:year/:month/:day/:title:output_ext

show_excerpts: true

moving:
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
