title: Willyywt's blog # name of the site
author: Willy (Yang Wentao) # name of site's author
url: https://willyangywt.cc # root address of the site
description: > # description of the site (multiple lines allowed)
  Willyywt (aka yang wentao)'s personal blog.

favicon: "favicon.ico" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

show_excerpts: true
search_index: true

# For footnotes
markdown: kramdown
kramdown:
  # https://stackoverflow.com/a/25597026/17956106
  smart_quotes: ["apos", "apos", "quot", "quot"]
  # Don't do anything at kramdown level
  # math_engine: +nil+

# Use rouge as syntax highlighter. (The original moving theme use https://highlightjs.org embeded in <head>)
# See rouge documentation: https://kramdown.gettalong.org/syntax_highlighter/rouge.html
# and jekyll documentation: https://jekyllrb.com/docs/liquid/tags/#code-snippet-highlighting
syntax_highlighter: rouge

moving:
  # Text shown for "return back to home page" link in the header
  back_to: "&lt;- Willyywt"
  # Source code link, used to display each page's source file. This link must have trailing slash '/'
  # Each page's source file link: {{ site.moving.source_url }}{{ page.path }}. page.path is overridable in front matter.
  # If page.moving_path_full is set then {{ page.moving_path_full }} is used instead  
  source_url: "https://github.com/willyywt/willyywt.github.io/tree/main/"

giscus:
  clientjs_url: "https://giscus.app/client.js"
  repo: "willyywt/willyywt.github.io"
  repo_id: "R_kgDOGLbo_g"
  category: "Announcements"
  category_id: "DIC_kwDOGLbo_s4CQb94"
  mapping: "pathname"
  strict: "1"
  reactions_enabled: "0"
  emit_metadata: "0"
  input_position: "top"
  # theme set by preferences, lang by page.lang | default: site.lang | default: "en"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

feed:
  posts_limit: 50

# https://jekyllrb.com/docs/configuration/front-matter-defaults/
# https://jekyllrb.com/docs/static-files/#add-front-matter-to-static-files
# Different permanlink value for pages and posts: https://stackoverflow.com/questions/41631082/can-jekyll-3-0-x-include-the-index-html-in-page-url/41632373#41632373
permalink: /:path/:title:output_ext
defaults:
  - scope:
      type: posts
    values:
      permalink: /posts/:year/:month/:day/:title:output_ext
  - scope:
      path: "article"
    values:
      is_page: true
  - scope:
      path: "tool"
    values:
      is_page: true
  - scope:
      path: "book"
    values:
      is_page: true
  - scope:
      path: "category"
    values:
      is_page: true
